<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE accounting [
<!ELEMENT accounting (note*)>
<!ELEMENT note (expense?, income?, date, quantity, concept)>
  <!ELEMENT expense (#PCDATA)>
  <!ELEMENT income (#PCDATA)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT quantity (#PCDATA)>
  <!ELEMENT concept (#PCDATA)>
]>


<accounting>
  <note>
    <income />
    <date> February 24 of 2011</date>
    <quantity>1800.00 €</quantity>
    <concept>Salary</concept>
  </note>
  <note>
    <expense />
    <date>February 28, 2011</date>
    <quantity >€74.25</quantity>
    <concept>Bill (electricity)</concept>
  </note>
</accounting>